version: "3.7"
services:
  app-core:
    build: .
    container_name: todo-app-core
    environment:
      - DB_PASS=pass
    ports:
      - 8000:8000
  db-core:
    image: postgres:13
    container_name: todo-db-core
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=core
    ports:
      - 5432:5432
